<?php

namespace Database\Seeders;

use App\Enums\Locale;
use App\Enums\TagType;
use Illuminate\Database\Seeder;
use Spatie\Tags\Tag;

class TagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $blueprint_tags = [
            TagType::BLUEPRINT_TAGS->value => [
                [
                    Locale::ENGLISH->value => 'Basic',
                    Locale::JAPANESE->value => '基本',
                    Locale::KOREAN->value => '기본',
                    Locale::TRADITIONAL_CHINESE->value => '基本',
                    Locale::SIMPLIFIED_CHINESE->value => '基础',
                    Locale::SPANISH->value => 'Básico',
                    Locale::PORTUGESE->value => 'Básico',
                    Locale::FRENCH->value => 'Basique',
                    Locale::GERMAN->value => 'Grundlegend',
                    Locale::RUSSIAN->value => 'Базовый',
                    Locale::ITALIAN->value => 'Base',
                    Locale::INDONESIAN->value => 'Dasar',
                    Locale::THAI->value => 'พื้นฐาน',
                    Locale::VIET->value => 'Cơ bản',
                ],
                [
                    Locale::ENGLISH->value => 'Advanced',
                    Locale::JAPANESE->value => '上級',
                    Locale::KOREAN->value => '고급',
                    Locale::TRADITIONAL_CHINESE->value => '進階',
                    Locale::SIMPLIFIED_CHINESE->value => '高级',
                    Locale::SPANISH->value => 'Avanzado',
                    Locale::PORTUGESE->value => 'Avançado',
                    Locale::FRENCH->value => 'Avancé',
                    Locale::GERMAN->value => 'Fortgeschritten',
                    Locale::RUSSIAN->value => 'Продвинутый',
                    Locale::ITALIAN->value => 'Avanzato',
                    Locale::INDONESIAN->value => 'Lanjutan',
                    Locale::THAI->value => 'ขั้นสูง',
                    Locale::VIET->value => 'Nâng cao',
                ],
                [
                    Locale::ENGLISH->value => 'Complex',
                    Locale::JAPANESE->value => '複雑',
                    Locale::KOREAN->value => '복잡함',
                    Locale::TRADITIONAL_CHINESE->value => '複雜',
                    Locale::SIMPLIFIED_CHINESE->value => '复杂',
                    Locale::SPANISH->value => 'Complejo',
                    Locale::PORTUGESE->value => 'Complexo',
                    Locale::FRENCH->value => 'Complexe',
                    Locale::GERMAN->value => 'Komplex',
                    Locale::RUSSIAN->value => 'Сложный',
                    Locale::ITALIAN->value => 'Complesso',
                    Locale::INDONESIAN->value => 'Kompleks',
                    Locale::THAI->value => 'ซับซ้อน',
                    Locale::VIET->value => 'Phức tạp',
                ],
                [
                    Locale::ENGLISH->value => 'Bottle',
                    Locale::JAPANESE->value => '瓶',
                    Locale::KOREAN->value => '병',
                    Locale::TRADITIONAL_CHINESE->value => '瓶子',
                    Locale::SIMPLIFIED_CHINESE->value => '瓶子',
                    Locale::SPANISH->value => 'Botella',
                    Locale::PORTUGESE->value => 'Garrafa',
                    Locale::FRENCH->value => 'Bouteille',
                    Locale::GERMAN->value => 'Flasche',
                    Locale::RUSSIAN->value => 'Бутылка',
                    Locale::ITALIAN->value => 'Bottiglia',
                    Locale::INDONESIAN->value => 'Botol',
                    Locale::THAI->value => 'ขวด',
                    Locale::VIET->value => 'Chai',
                ],
                [
                    Locale::ENGLISH->value => 'Parts',
                    Locale::JAPANESE->value => '部品',
                    Locale::KOREAN->value => '부품',
                    Locale::TRADITIONAL_CHINESE->value => '零件',
                    Locale::SIMPLIFIED_CHINESE->value => '零件',
                    Locale::SPANISH->value => 'Piezas',
                    Locale::PORTUGESE->value => 'Peças',
                    Locale::FRENCH->value => 'Pièces',
                    Locale::GERMAN->value => 'Teile',
                    Locale::RUSSIAN->value => 'Детали',
                    Locale::ITALIAN->value => 'Parti',
                    Locale::INDONESIAN->value => 'Suku cadang',
                    Locale::THAI->value => 'ชิ้นส่วน',
                    Locale::VIET->value => 'Bộ phận',
                ],
                [
                    Locale::ENGLISH->value => 'Meds',
                    Locale::JAPANESE->value => '医薬品',
                    Locale::KOREAN->value => '의약품',
                    Locale::TRADITIONAL_CHINESE->value => '藥品',
                    Locale::SIMPLIFIED_CHINESE->value => '药品',
                    Locale::SPANISH->value => 'Medicamentos',
                    Locale::PORTUGESE->value => 'Medicamentos',
                    Locale::FRENCH->value => 'Médicaments',
                    Locale::GERMAN->value => 'Medikamente',
                    Locale::RUSSIAN->value => 'Лекарства',
                    Locale::ITALIAN->value => 'Medicine',
                    Locale::INDONESIAN->value => 'Obat',
                    Locale::THAI->value => 'ยา',
                    Locale::VIET->value => 'Thuốc',
                ],
                [
                    Locale::ENGLISH->value => 'Food',
                    Locale::JAPANESE->value => '食料',
                    Locale::KOREAN->value => '식품',
                    Locale::TRADITIONAL_CHINESE->value => '食物',
                    Locale::SIMPLIFIED_CHINESE->value => '食物',
                    Locale::SPANISH->value => 'Comida',
                    Locale::PORTUGESE->value => 'Comida',
                    Locale::FRENCH->value => 'Nourriture',
                    Locale::GERMAN->value => 'Lebensmittel',
                    Locale::RUSSIAN->value => 'Еда',
                    Locale::ITALIAN->value => 'Cibo',
                    Locale::INDONESIAN->value => 'Makanan',
                    Locale::THAI->value => 'อาหาร',
                    Locale::VIET->value => 'Thức ăn',
                ],
                [
                    Locale::ENGLISH->value => 'Gear',
                    Locale::JAPANESE->value => '装備',
                    Locale::KOREAN->value => '장비',
                    Locale::TRADITIONAL_CHINESE->value => '裝備',
                    Locale::SIMPLIFIED_CHINESE->value => '装备',
                    Locale::SPANISH->value => 'Equipo',
                    Locale::PORTUGESE->value => 'Equipamento',
                    Locale::FRENCH->value => 'Équipement',
                    Locale::GERMAN->value => 'Ausrüstung',
                    Locale::RUSSIAN->value => 'Снаряжение',
                    Locale::ITALIAN->value => 'Equipaggiamento',
                    Locale::INDONESIAN->value => 'Peralatan',
                    Locale::THAI->value => 'อุปกรณ์',
                    Locale::VIET->value => 'Thiết bị',
                ],
                [
                    Locale::ENGLISH->value => 'Battery',
                    Locale::JAPANESE->value => 'バッテリー',
                    Locale::KOREAN->value => '배터리',
                    Locale::TRADITIONAL_CHINESE->value => '電池',
                    Locale::SIMPLIFIED_CHINESE->value => '电池',
                    Locale::SPANISH->value => 'Batería',
                    Locale::PORTUGESE->value => 'Bateria',
                    Locale::FRENCH->value => 'Batterie',
                    Locale::GERMAN->value => 'Batterie',
                    Locale::RUSSIAN->value => 'Батарея',
                    Locale::ITALIAN->value => 'Batteria',
                    Locale::INDONESIAN->value => 'Baterai',
                    Locale::THAI->value => 'แบตเตอรี่',
                    Locale::VIET->value => 'Pin',
                ],
                [
                    Locale::ENGLISH->value => 'Power',
                    Locale::JAPANESE->value => '電力',
                    Locale::KOREAN->value => '전력',
                    Locale::TRADITIONAL_CHINESE->value => '電力',
                    Locale::SIMPLIFIED_CHINESE->value => '电力',
                    Locale::SPANISH->value => 'Energía',
                    Locale::PORTUGESE->value => 'Energia',
                    Locale::FRENCH->value => 'Puissance',
                    Locale::GERMAN->value => 'Strom',
                    Locale::RUSSIAN->value => 'Энергия',
                    Locale::ITALIAN->value => 'Energia',
                    Locale::INDONESIAN->value => 'Daya',
                    Locale::THAI->value => 'พลังงาน',
                    Locale::VIET->value => 'Năng lượng',
                ],
                [
                    Locale::ENGLISH->value => 'Seed',
                    Locale::JAPANESE->value => '種',
                    Locale::KOREAN->value => '씨앗',
                    Locale::TRADITIONAL_CHINESE->value => '種子',
                    Locale::SIMPLIFIED_CHINESE->value => '种子',
                    Locale::SPANISH->value => 'Semilla',
                    Locale::PORTUGESE->value => 'Semente',
                    Locale::FRENCH->value => 'Graine',
                    Locale::GERMAN->value => 'Samen',
                    Locale::RUSSIAN->value => 'Семя',
                    Locale::ITALIAN->value => 'Seme',
                    Locale::INDONESIAN->value => 'Benih',
                    Locale::THAI->value => 'เมล็ดพันธุ์',
                    Locale::VIET->value => 'Hạt giống',
                ],
                [
                    Locale::ENGLISH->value => 'Plant',
                    Locale::JAPANESE->value => '植物',
                    Locale::KOREAN->value => '식물',
                    Locale::TRADITIONAL_CHINESE->value => '植物',
                    Locale::SIMPLIFIED_CHINESE->value => '植物',
                    Locale::SPANISH->value => 'Planta',
                    Locale::PORTUGESE->value => 'Planta',
                    Locale::FRENCH->value => 'Plante',
                    Locale::GERMAN->value => 'Pflanze',
                    Locale::RUSSIAN->value => 'Растение',
                    Locale::ITALIAN->value => 'Pianta',
                    Locale::INDONESIAN->value => 'Tanaman',
                    Locale::THAI->value => 'พืช',
                    Locale::VIET->value => 'Cây trồng',
                ],
                [
                    Locale::ENGLISH->value => 'Grind',
                    Locale::JAPANESE->value => '研磨',
                    Locale::KOREAN->value => '분쇄',
                    Locale::TRADITIONAL_CHINESE->value => '研磨',
                    Locale::SIMPLIFIED_CHINESE->value => '研磨',
                    Locale::SPANISH->value => 'Moler',
                    Locale::PORTUGESE->value => 'Moagem',
                    Locale::FRENCH->value => 'Moudre',
                    Locale::GERMAN->value => 'Mahlen',
                    Locale::RUSSIAN->value => 'Дробить',
                    Locale::ITALIAN->value => 'Macinare',
                    Locale::INDONESIAN->value => 'Menggiling',
                    Locale::THAI->value => 'บด',
                    Locale::VIET->value => 'Xay nghiền',
                ],
                [
                    Locale::ENGLISH->value => 'Explosive',
                    Locale::JAPANESE->value => '爆発物',
                    Locale::KOREAN->value => '폭발물',
                    Locale::TRADITIONAL_CHINESE->value => '爆裂物',
                    Locale::SIMPLIFIED_CHINESE->value => '爆炸物',
                    Locale::SPANISH->value => 'Explosivo',
                    Locale::PORTUGESE->value => 'Explosivo',
                    Locale::FRENCH->value => 'Explosif',
                    Locale::GERMAN->value => 'Sprengstoff',
                    Locale::RUSSIAN->value => 'Взрывчатка',
                    Locale::ITALIAN->value => 'Esplosivo',
                    Locale::INDONESIAN->value => 'Bahan peledak',
                    Locale::THAI->value => 'วัตถุระเบิด',
                    Locale::VIET->value => 'Thuốc nổ',
                ],
                [
                    Locale::ENGLISH->value => 'Xiranite',
                    Locale::JAPANESE->value => 'ジラナイト',
                    Locale::KOREAN->value => '지라나이트',
                    Locale::TRADITIONAL_CHINESE->value => '息壤',
                    Locale::SIMPLIFIED_CHINESE->value => '息壤',
                    Locale::SPANISH->value => 'Xiranita',
                    Locale::PORTUGESE->value => 'Xiranita',
                    Locale::FRENCH->value => 'Xiranite',
                    Locale::GERMAN->value => 'Xiranit',
                    Locale::RUSSIAN->value => 'Ксиранит',
                    Locale::ITALIAN->value => 'Xiranite',
                    Locale::INDONESIAN->value => 'Xiranite',
                    Locale::THAI->value => 'ไซราไนต์',
                    Locale::VIET->value => 'Xiranite',
                ],
                [
                    Locale::ENGLISH->value => 'Other',
                    Locale::JAPANESE->value => 'その他',
                    Locale::KOREAN->value => '기타',
                    Locale::TRADITIONAL_CHINESE->value => '其他',
                    Locale::SIMPLIFIED_CHINESE->value => '其他',
                    Locale::SPANISH->value => 'Otro',
                    Locale::PORTUGESE->value => 'Outro',
                    Locale::FRENCH->value => 'Autre',
                    Locale::GERMAN->value => 'Andere',
                    Locale::RUSSIAN->value => 'Другое',
                    Locale::ITALIAN->value => 'Altro',
                    Locale::INDONESIAN->value => 'Lainnya',
                    Locale::THAI->value => 'อื่นๆ',
                    Locale::VIET->value => 'Khác',
                ],
            ],
            TagType::BLUEPRINT_TIER->value => [
                [
                    Locale::ENGLISH->value => 'I',
                    Locale::JAPANESE->value => 'I',
                    Locale::KOREAN->value => 'I',
                    Locale::TRADITIONAL_CHINESE->value => 'I',
                    Locale::SIMPLIFIED_CHINESE->value => 'I',
                    Locale::SPANISH->value => 'I',
                    Locale::PORTUGESE->value => 'I',
                    Locale::FRENCH->value => 'I',
                    Locale::GERMAN->value => 'I',
                    Locale::RUSSIAN->value => 'I',
                    Locale::ITALIAN->value => 'I',
                    Locale::INDONESIAN->value => 'I',
                    Locale::THAI->value => 'I',
                    Locale::VIET->value => 'I',
                ],
                [
                    Locale::ENGLISH->value => 'II',
                    Locale::JAPANESE->value => 'II',
                    Locale::KOREAN->value => 'II',
                    Locale::TRADITIONAL_CHINESE->value => 'II',
                    Locale::SIMPLIFIED_CHINESE->value => 'II',
                    Locale::SPANISH->value => 'II',
                    Locale::PORTUGESE->value => 'II',
                    Locale::FRENCH->value => 'II',
                    Locale::GERMAN->value => 'II',
                    Locale::RUSSIAN->value => 'II',
                    Locale::ITALIAN->value => 'II',
                    Locale::INDONESIAN->value => 'II',
                    Locale::THAI->value => 'II',
                    Locale::VIET->value => 'II',
                ],
                [
                    Locale::ENGLISH->value => 'III',
                    Locale::JAPANESE->value => 'III',
                    Locale::KOREAN->value => 'III',
                    Locale::TRADITIONAL_CHINESE->value => 'III',
                    Locale::SIMPLIFIED_CHINESE->value => 'III',
                    Locale::SPANISH->value => 'III',
                    Locale::PORTUGESE->value => 'III',
                    Locale::FRENCH->value => 'III',
                    Locale::GERMAN->value => 'III',
                    Locale::RUSSIAN->value => 'III',
                    Locale::ITALIAN->value => 'III',
                    Locale::INDONESIAN->value => 'III',
                    Locale::THAI->value => 'III',
                    Locale::VIET->value => 'III',
                ],
                [
                    Locale::ENGLISH->value => 'IV',
                    Locale::JAPANESE->value => 'IV',
                    Locale::KOREAN->value => 'IV',
                    Locale::TRADITIONAL_CHINESE->value => 'IV',
                    Locale::SIMPLIFIED_CHINESE->value => 'IV',
                    Locale::SPANISH->value => 'IV',
                    Locale::PORTUGESE->value => 'IV',
                    Locale::FRENCH->value => 'IV',
                    Locale::GERMAN->value => 'IV',
                    Locale::RUSSIAN->value => 'IV',
                    Locale::ITALIAN->value => 'IV',
                    Locale::INDONESIAN->value => 'IV',
                    Locale::THAI->value => 'IV',
                    Locale::VIET->value => 'IV',
                ],
            ],
            TagType::BLUEPRINT_TYPE->value => [
                [
                    Locale::ENGLISH->value => 'PAC',
                    Locale::JAPANESE->value => 'PAC',
                    Locale::KOREAN->value => 'PAC',
                    Locale::TRADITIONAL_CHINESE->value => 'PAC',
                    Locale::SIMPLIFIED_CHINESE->value => '生产',
                    Locale::SPANISH->value => 'PAC',
                    Locale::PORTUGESE->value => 'PAC',
                    Locale::FRENCH->value => 'PAC',
                    Locale::GERMAN->value => 'PAC',
                    Locale::RUSSIAN->value => 'PAC',
                    Locale::ITALIAN->value => 'PAC',
                    Locale::INDONESIAN->value => 'PAC',
                    Locale::THAI->value => 'PAC',
                    Locale::VIET->value => 'PAC',
                ],
                [
                    Locale::ENGLISH->value => 'Sub-PAC',
                    Locale::JAPANESE->value => 'Sub-PAC',
                    Locale::KOREAN->value => 'Sub-PAC',
                    Locale::TRADITIONAL_CHINESE->value => 'Sub-PAC',
                    Locale::SIMPLIFIED_CHINESE->value => '研究',
                    Locale::SPANISH->value => 'Sub-PAC',
                    Locale::PORTUGESE->value => 'Sub-PAC',
                    Locale::FRENCH->value => 'Sub-PAC',
                    Locale::GERMAN->value => 'Sub-PAC',
                    Locale::RUSSIAN->value => 'Sub-PAC',
                    Locale::ITALIAN->value => 'Sub-PAC',
                    Locale::INDONESIAN->value => 'Sub-PAC',
                    Locale::THAI->value => 'Sub-PAC',
                    Locale::VIET->value => 'Sub-PAC',
                ],
            ],
        ];

        foreach ($blueprint_tags as $type => $tags) {
            foreach ($tags as $tag) {
                $englishName = $tag[Locale::ENGLISH->value];
                Tag::create([
                    'name' => $tag,
                    'slug' => str($englishName)->slug(),
                    'type' => $type,
                ]);
            }
        }
    }
}
